### ISSUE TITLE
Agent dependencies

### ISSUE THREAD

**Issue by jacksondc** [yasserfarouk/scml#75]
We're trying to upload our agent, which depends on xgboost. We've included xgboost in our dependencies list, but the test comes back with the error

```
EXCEPTION
Failed on: 2021-08-01 20:30:24.065072 UTC
No module named xgboost
Traceback (most recent call last):
File "./python/runagent.py", line 169, in main
agent_class = get_class(class_name, module_name=module_name)
File "/vol/home/ymohamm1/scmlweb/python/.venv/lib/python3.8/site-packages/negmas/helpers.py", line 1082, in get_class
module = importlib.import_module(module_name)
File "/home/ymohamm1/.pyenv/versions/3.8.10/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1014, in _gcd_import
File "", line 991, in _find_and_load
File "", line 975, in _find_and_load_unlocked
File "", line 671, in _load_unlocked
File "", line 848, in exec_module
File "", line 219, in _call_with_frames_removed
File "/vol/home/ymohamm1/scmlweb/agents/team_corleone/godfather/godfather.py", line 59, in
import xgboost as xgb
ModuleNotFoundError: No module named xgboost

DEBUGGING INFO
PATH: /vol/home/ymohamm1/scmlweb/storage/app/files/team_corleone/202181824242424__20092__GodfatherGoldfish__0.0.4.zip
Class Name: GoldfishParetoEmpiricalGodfatherAgent
team_id: team_corleone
team_name: Team Corleone
apath: godfather.godfather
MODULE NAME: godfather.godfather
END OF REPORT
```

Dependencies list: `numpy;tabulate;time;copy;typing;enum;random;warnings;xgboost;pandas;pathlib`.

Any idea what we're doing wrong?

**Comment by yasserfarouk** [comment]
Firstly, do not worry. The code is on the server. Secondly, the test server may have failed xgboost installation. Will resolve it soon. Please try again in 15 min

**Comment by yasserfarouk** [comment]
xgboost was installed!!
Do you still face the same issue?

**Comment by jacksondc** [comment]
Working now! Thank you!
